module.exports = {
    FB_PAGE_TOKEN: 'EAAYd9QVeZAB0BAHBUJLarGdBM1HSOZCLVV9xEQui7DUDIofLfScNTnBRYcuZANSnxCnw3eGcWN3LxooxN7pWjojut4KmxuvAC7B6WZBugYVYpDM4ZBl4vYv5tifLMJblAjp9lKI9Sud0NbiSQynaJq6s9WmUsmsthGMDtLrN9Iu5qCHZAZCNHnn',
    FB_VERIFY_TOKEN: '',
    API_AI_CLIENT_ACCESS_TOKEN: '',
    FB_APP_SECRET: '',
    SERVER_URL: "",
};